MiPrimeraAplicacionConEntityFramework/Models/Empleado.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimeraAplicacionConEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int IIDEMPLEADO { get; set; }
        public string NOMBRE { get; set; }
        public string APPATERNO { get; set; }
        public string APMATERNO { get; set; }
        public Nullable<System.DateTime> FECHACONTRATO { get; set; }
        public Nullable<decimal> SUELDO { get; set; }
        public Nullable<int> IIDTIPOUSUARIO { get; set; }
        public Nullable<int> IIDTIPOCONTRATO { get; set; }
        public Nullable<int> IIDSEXO { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public Nullable<int> bTieneUsuario { get; set; }
        public string TIPOUSUARIO { get; set; }
    
        public virtual Sexo Sexo { get; set; }
        public virtual TipoUsuario TipoUsuario1 { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
        public virtual TIPOUSUARIOREGISTRO TIPOUSUARIOREGISTRO { get; set; }
    }
}

MiPrimeraAplicacionConEntityFramework/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiPrimeraAplicacionConEntityFramework.Models;
namespace MiPrimeraAplicacionConEntityFramework.Controllers
{
    public class EmpleadoController : Controller
    {
        // GET: Empleado
        public ActionResult Index()
        {
            List<EmpleadoCLS> listaEmpleado = null;
            using (var db = new BDPasajeEntities())
            {
                listaEmpleado = (from empleado in db.Empleado
                                 join tipoUsuario in db.TipoUsuario
                                 on empleado.IIDTIPOUSUARIO equals tipoUsuario.IIDTIPOUSUARIO
                                 join tipoContrato in db.TipoContrato
                                 on empleado.IIDTIPOCONTRATO equals tipoContrato.IIDTIPOCONTRATO
                                 select new EmpleadoCLS
                                 {
                                     iidEmpleado = empleado.IIDEMPLEADO,
                                     nombre = empleado.NOMBRE,
                                     apPaterno = empleado.APPATERNO,
                                     apMaterno = empleado.APMATERNO,
                                     nombreTipoUsuario = tipoUsuario.NOMBRE,
                                     nombreTipoContrato = tipoContrato.NOMBRE

                                 }).ToList();
            }
            return View(listaEmpleado);
        }
        public void listarComboSexo()
        {
            //Agregar listado
            List<SelectListItem> lista;
                using (var db = new BDPasajeEntities()){
                lista = (from sexo in db.Sexo
                         where sexo.BHABILITADO == 1
                         select new SelectListItem
                         {
                             Text = sexo.NOMBRE,
                             Value = sexo.IIDSEXO.ToString()
                         }).ToList();
                lista.Insert(0,new SelectListItem{ Text ="--Selecione--",Value=""});
                ViewBag.listaSexo = lista;
                }
        }

        public void listaTipoContrato()
        {
            //Agregar listado de tipo contrato
            List<SelectListItem> lista;
            using (var db = new BDPasajeEntities())
            {
                lista = (from tipoContrato in db.TipoContrato
                         where tipoContrato.BHABILITADO == 1
                         select new SelectListItem
                         {
                             Text = tipoContrato.NOMBRE,
                             Value = tipoContrato.IIDTIPOCONTRATO.ToString()
                         }).ToList();
                lista.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
                ViewBag.listaTipoContrato = lista;
            }
        }
        public void listaTipoUsuario()
        {
            //Agregar listado de tipos de usuario
            List<SelectListItem> lista;
            using (var db = new BDPasajeEntities())
            {
                lista = (from tipoUsuario in db.TipoUsuario
                         where tipoUsuario.BHABILITADO == 1
                         select new SelectListItem
                         {
                             Text = tipoUsuario.NOMBRE,
                             Value = tipoUsuario.IIDTIPOUSUARIO.ToString()
                         }).ToList();
                lista.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
                ViewBag.listaTipoUsuario = lista;
            }
        }
        public void listarCombos()
        {
            listaTipoUsuario();
            listaTipoContrato();
            listarComboSexo();
        }
        public ActionResult Agregar()
        {
            listarCombos();
            return View();        
        }
        [HttpPost]
        public ActionResult Agregar(EmpleadoCLS oEmpleadoCLS)
        {
            if (!ModelState.IsValid)
            {
                listarCombos();
                return View(oEmpleadoCLS);
            }
            using (var db = new BDPasajeEntities())
            {
                Empleado oEmpleado = new Empleado();
                oEmpleado.NOMBRE = oEmpleadoCLS.nombre;
                oEmpleado.APPATERNO = oEmpleadoCLS.apPaterno;
                oEmpleado.APMATERNO = oEmpleadoCLS.apMaterno;
                oEmpleado.FECHACONTRATO = oEmpleadoCLS.fechaContrato;
                oEmpleado.SUELDO = oEmpleadoCLS.sueldo;
                oEmpleado.IIDTIPOUSUARIO = oEmpleadoCLS.iidtipoUsuario;
                oEmpleado.IIDTIPOCONTRATO = oEmpleadoCLS.iidtipoContrato;
                oEmpleado.IIDSEXO = oEmpleadoCLS.iidsexo;
                oEmpleado.BHABILITADO = 1;
                db.Empleado.Add(oEmpleado);
                db.SaveChanges();

            }
            return RedirectToAction("Index");
        }
    }
}

MiPrimeraAplicacionConEntityFramework/Views/Empleado/Agregar.cshtml
@using MiPrimeraAplicacionConEntityFramework.Models
@model EmpleadoCLS

@{
    ViewBag.Title = "Agregar";
    List<SelectListItem> listaSexo = (List<SelectListItem>)ViewBag.listaSexo;
    List<SelectListItem> listaTipoContrato = (List<SelectListItem>)ViewBag.listaTipoContrato;
    List<SelectListItem> listaTipoUsuario = (List<SelectListItem>)ViewBag.listaTipoUsuario;
}

<h2>Agregar</h2>
<div class="row">

    <div class="col-md-6">

        @using(Html.BeginForm("Agregar", "Empleado", FormMethod.Post))
        {
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.apPaterno)
                @Html.TextBoxFor(p => p.apPaterno, new { @class = "form-control" })
                @Html.ValidationMessage("apPaterno", new { @class = "text-danger" })
            </div>
            <div>|
                @Html.LabelFor(p => p.apMaterno)
                @Html.TextBoxFor(p => p.apMaterno, new { @class = "form-control" })
                @Html.ValidationMessage("apMaterno", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.fechaContrato)
                @Html.EditorFor(p => p.fechaContrato, new { htmlAttributes= new { @class = "form-control" } })
                @Html.ValidationMessage("fechaContrato", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.sueldo)
                @Html.TextBoxFor(p => p.sueldo, new { @class = "form-control" })
                @Html.ValidationMessage("sueldo", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.iidtipoUsuario)
                @Html.DropDownList("iidtipoUsuario", listaTipoUsuario, null, new { @class = "form-control" })
                @Html.ValidationMessage("iidtipoUsuario", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.iidtipoContrato)
                @Html.DropDownList("iidtipoContrato", listaTipoContrato, null, new { @class = "form-control" })
                @Html.ValidationMessage("iidtipoContrato", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.iidsexo)
                @Html.DropDownList("iidSexo", listaSexo, null, new { @class = "form-control" })
                @Html.ValidationMessage("iidSexo", new { @class = "text-danger" })
            </div>
            <input type="submit" value="Enviar" class="btn btn-primary"/>
        }

    </div>
</div>

MiPrimeraAplicacionConEntityFramework/Views/Empleado/Index.cshtml
@using MiPrimeraAplicacionConEntityFramework.Models
@model List<EmpleadoCLS>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Agregar", "Agregar", "Empleado", null, new { @class = "btn btn-primary" })
<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <td>@Html.LabelFor(p => Model[0].iidEmpleado)</td>
            <td>@Html.LabelFor(p => Model[0].nombre)</td>
            <td>@Html.LabelFor(p => Model[0].apPaterno)</td>
            <td>@Html.LabelFor(p => Model[0].nombreTipoUsuario)</td>
            <td>@Html.LabelFor(p => Model[0].nombreTipoContrato)</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.iidEmpleado</td>
                <td>@item.nombre</td>
                <td>@item.apPaterno</td>
                <td>@item.nombreTipoUsuario</td>
                <td>@item.nombreTipoContrato</td>
            </tr>
        }
    </tbody>
</table>