MiPrimeraAplicacionConEntityFramework/Models/Sucursal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimeraAplicacionConEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sucursal()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDSUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHAAPERTURA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

MiPrimeraAplicacionConEntityFramework/Controllers/SucursalController.cs
using MiPrimeraAplicacionConEntityFramework.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiPrimeraAplicacionConEntityFramework.Controllers
{
    public class SucursalController : Controller
    {
        // GET: Sucursal
        public ActionResult Index()
        {
            List<SucursalCLS> listaSucursal = null;
            using (var db = new BDPasajeEntities())
            {
                listaSucursal = (from sucursal in db.Sucursal
                                 where sucursal.BHABILITADO == 1
                                 select new SucursalCLS
                                 {
                                     iidsucursal = sucursal.IIDSUCURSAL,
                                     nombre = sucursal.NOMBRE,
                                     telefono = sucursal.TELEFONO,
                                     email = sucursal.EMAIL
                                 }).ToList();
            }
            return View(listaSucursal);
        }
        public ActionResult Agregar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Agregar(SucursalCLS oSucursalCLS)
        {
            if (!ModelState.IsValid)
            {
                return View(oSucursalCLS);
            }
            using (var db = new BDPasajeEntities())
            {
                Sucursal oSucursal = new Sucursal();
                oSucursal.NOMBRE = oSucursalCLS.nombre;
                oSucursal.DIRECCION = oSucursalCLS.direccion;
                oSucursal.TELEFONO = oSucursalCLS.telefono;
                oSucursal.EMAIL = oSucursalCLS.email;
                oSucursal.FECHAAPERTURA = oSucursalCLS.fechaApertura;
                oSucursal.BHABILITADO = 1;
                db.Sucursal.Add(oSucursal);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
            
        }
    }
}

MiPrimeraAplicacionConEntityFramework/Views/Sucursal/Agregar.cshtml
@using MiPrimeraAplicacionConEntityFramework.Models
@model SucursalCLS
@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Sucursal", FormMethod.Post))
        {
        <div>
            @Html.LabelFor(p => p.nombre)
            @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
            @Html.ValidationMessage("nombre", new { @class = "text-danger" })
        </div>

        <div>
            @Html.LabelFor(p => p.direccion)
            @Html.TextBoxFor(p => p.direccion, new { @class = "form-control" })
            @Html.ValidationMessage("direccion", new { @class = "text-danger" })
        </div>

        <div>
            @Html.LabelFor(p => p.telefono)
            @Html.TextBoxFor(p => p.telefono, new { @class = "form-control" })
            @Html.ValidationMessage("telefono", new { @class = "text-danger" })
        </div>

        <div>
            @Html.LabelFor(p => p.email)
            @Html.TextBoxFor(p => p.email, new { @class = "form-control" })
            @Html.ValidationMessage("email", new { @class = "text-danger" })
        </div>

        <div>
            @Html.LabelFor(p => p.fechaApertura)
            @Html.EditorFor(p => p.fechaApertura, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessage("fechaApertura", new { @class = "text-danger" })
        </div>      
        <div style="margin:auto">
            <input  type="submit" class="btn btn-primary" value="Enviar" />
        </div>
    }

    </div>

    
</div>

MiPrimeraAplicacionConEntityFramework/Views/Sucursal/Index.cshtml
@using MiPrimeraAplicacionConEntityFramework.Models
@model List<SucursalCLS>
@{
    ViewBag.Title = "Index";
}

@Html.ActionLink("Agregar", "Agregar", "Sucursal", null, new { @class = "btn btn-primary" })
<h2>Index</h2>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>@Html.LabelFor(p => Model[0].iidsucursal)</td>
            <td>@Html.LabelFor(p => Model[0].nombre)</td>
            <td>@Html.LabelFor(p => Model[0].telefono)</td>
            <td>@Html.LabelFor(p => Model[0].email)</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.iidsucursal</td>
                <td>@item.nombre</td>
                <td>@item.telefono</td>
                <td>@item.email</td>
            </tr>
        }
    </tbody>
</table>